# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RYycj3Wua8Qo4E8mYTXqnhrNCTsbatim

Algoritmo 1
"""

#solicitar al usuario que ingrese su nombre
nombre = input("Por favor, ingresa tu nombre: ")

#imprimir un saludo personalizado
print ("Hooola ", nombre + " Welcome to Brazil.")

"""Algoritmo 2"""

#Solicitar al usurariio que ingrese su edad
edad = int(input("Por favor, ingresa tu edad: "))

#calcular el año de nacimiento
anio_actual = 2024
anio_nacimiento = anio_actual - edad

# Imprimir el año de nacimiento
print("Tu año de nacimiento es: ", anio_nacimiento)

"""Algoritmo 3"""

#solicitar al usuario que ingrese un numero entero
numero = int(input("Por favor, ingrese un numero entero: "))

#verificar si el numero es positivo o negativo
if numero > 0:
  print("El numero es positivo")
elif numero == 0:
    print("El numero es cero.")
else:
  print("El numero es negativo.")

"""Algoritmo 4

"""

#imprimir los numeros del 1 al 100
for numero in range(1, 101):
  print(numero)

"""algoritmo 5"""

#Definir la contraseña deseada
contrasena_correcta = "burritosabanero53"

#Solicitar la contraseña al usuario
while True:
  contrasena_ingresada = input("Ingrese la contraseña: ")

  #verificar si la contraseña ingresada es correcta
  if contrasena_ingresada == contrasena_correcta:
    print("¡Contraseña correcta! Acceso permitiddo. ")
    break #sañor del bucle si la contraseña es correcta
  else:
    print("Contraseña incorrecta. Intentelo nuevamente.")